fig.fish
tools/install_and_upgrade.sh

Fix 
When exiting a fish process the user receives a warning that fig bg:exec is running in background.
No warning!
Also contains the new /specs download URL

Fix fish warning by disowning background process

---

README.md

Docs update
When clicking on withfig/fig-apps it actually takes to autocomplete repo, but it should take to fig-apps repo
Take the user to the withfig/fig-apps repository page

Fix link to fig-apps

---

fig.sh
shell/post.bash
shell/pre.fish
shell/pre.sh

Fixes issue where shell created by figterm does not mirror login attribute of parent shell.

Pass login shell to figterm and clean up env variables

---

tools/all-settings.json

Bug fix
Fig currently autocompletes for all commands, even commands that are listed under the "Disable Fig for specific CLI Tools" setting due to an incorrect format.
Shows the user the correct format to disable autocomplete for certain CLI tools. Fig autocomplete should not show up for CLI tools that are added to this setting: "Disable Fig for specific CLI Tools"
- Addresses https://github.com/withfig/fig/issues/285

Changed details for disable command to fix settings app

---

tools/install_and_upgrade.sh

Bug fix
Certain escape characters will end bash input, which can lead to only parts of user's dotfiles being kept when we prepend.
Replace echo with cat to ensure no parts of user's dotfiles are lost

Prefer cat to echo for unknown input

---

tools/install_and_upgrade.sh

Bug fix
Re: https://github.com/withfig/fig/issues/343
The sourcing line will sometimes be appended to a non-empty line, causing unpredictable bugs
Always add a newline before the ENV VAR lines to each config file

Add newline to ensure Fig isn't appended to existing lines

---

tools/install_and_upgrade.sh

Dotfiles are unrecoverable if something goes wrong in the installation process.
Backup any file touched before modifying it in a timestamped backup folder.
SSH config modification is not done by the install and upgrade script so this file is not included in the backup right now

Add backup of dotfiles every time install script is run

---

shell/pre.sh
tools/install_and_upgrade.sh

Bugfix
Sometimes on update, `figterm` will consistently crash when launching new terminal sessions.
Delete old `$SHELL (figterm)` binaries because this seems to resolve the issue (TBD whether or not this is true)

Delete figterm artifacts

---

tools/all-settings.json

Feature
There is no way of customizing the fontFamily of the autocomplete window

feat: add autocomplete.fontFamily setting

---

tools/install_and_upgrade.sh

Fixes #41 
TMUX integration always writes to ~/.tmux.conf
TMUX integration will append to ~/.tmux.conf.local if it exists, otherwise will write to ~/.tmux.conf

fix: write to .tmux.conf.local if it exists

---

shell/post.zsh

Hotfix
When the `stty` setting `istrip` is enabled, inserting text in `zsh` using `fig` will result in`'` or an `(` character instead of the intended text.
This is because we do text insertion in ZSH by binding a `fig_insert` function to the `◧` character. 
We reset the `istrip` setting to off on every line using the zsh `pre_prompt` hook.

Add workaround for istrip bug

---

shell/post.zsh

Prevent error message "stdin is not a terminal"

---

tools/cli/debug.sh
tools/cli/email_dotfiles.sh

Basic curl command to email all zsh and bash dotfiles.
Logic for parsing and emailing dotfiles as attachments handled in /dotfiles route of backend.
Resulting email to hello@fig.io after script is run:
User is also CC'd on the email.
See: https://github.com/withfig/core-backend/pull/13

CLI tool to email dotfiles

---

tools/uninstall-script.sh

Fixes uninstall script not removing fig lines from all dotfiles
Script originally passed a list of files to sed to remove patterns. If one of those files did not exist, sed would not run on the remaining files.
Instead of passing a list of files, we explicitly loop over the files so that the removal is done on each regardless of whether it fails on one.
Also added code to:
* Remove pre.sh line
* Remove "This line must be at start|end" comments
Re: https://linear.app/fig/issue/ENG-1580/ensure-that-uninstall-script-fully-removes-shell-integration-from

Continue uninstallation on "no file" error

---

shell/pre.sh
tools/install_and_upgrade.sh

Bug fix
We currently copy `figterm` binary at runtime
Copy (and rename) on install
This solves issues related to permissioning

Rename figterm binaries on install

---

fig.sh
shell/pre.sh

Bug fix / Feature
Fig won't run within Warp.
This adds cross compatibility to ensure that Fig continues to function except from within Warp.
Self explanatory.

Prevent Fig from starting when ran from Warp.

---

shell/post.zsh
tools/doctor.sh

The right prompt missing and af-magic incompatibility were actually 2 separate issues.
The right prompt can be set in zsh by modifying either RPS1 or RPROMPT. These 2 variables do the exact thing but are not linked. If RPS1 is set, RPROMPT could be unset and vice versa. 
In our post.zsh, we copied RPS1 then added it back in. If the user used RPROMPT to set their right prompt, we were ignoring it so it would be missing entirely.
Changed post.zsh to copy whichever variable was set.
The af-magic right prompt is set:
```bash
RPS1='${return_code}'
(( $+functions[virtualenv_prompt_info] )) && RPS1+='$(virtualenv_prompt_info)'
RPS1+=' $my_gray%n@%m%{$reset_color%}%'
```
The 3rd line escapes the prompt with a final '%'. When we add back in RPS1, we expand it with another '%' which mangles the …

Fix right prompt issues

---

tools/doctor.sh

Fix tmux integration check. Missing file arg to grep caused switch to break early.
Update macOS version check for OS version earlier than Mojave.
Add check for Bitwarden desktop < 1.28.0. Old versions had a bug that enabled secure keyboard entry in the background.

Fixes and additional checks for fig doctor

---

tools/cli/contribute.sh
tools/cli/debug.sh
tools/cli/issue.sh

Docs: Use 'GitHub' instead of 'Github'

---

tools/cli/list.sh

Specs are now served from skypack so looking at local specs is outdated
Using GitHub API to get list of directories in /src on master @ latest
Does not recursively list subdirectories
Mimics output of current fig list
Re: https://linear.app/fig/issue/ENG-1682/update-fig-list-for-skypack

Get list of specs from remote repo

---

shell/zle.zsh

This is a workaround for a bug in add-zle-hook-widget
1. fast-syntax-highlighting and zsh-history-substring-search make `$widgets[<hook>]` equal to `user:_zsh_highlight_widget_orig-s000-r<integer>-zle-<hook>`
2. which causes `[[ ${widgets[$hook]:-} != "user:azhw:$hook" ]]` in add-zle-hook-widget to evaluate to true
3. which in turn causes add-zle-hook-widget to add the same widget again to the list
4. so that the wrapped `zle-<hook>` widget now ends up calling itself.
This workaround ensures we don't call add-zle-hook-widget until these plugins have been sourced.
More info on add-zle-hook-widget bug: https://www.zsh.org/mla/workers/2021/msg01310.html
Fix: https://github.com/withfig/fig/issues/94

Workaround for zim, z-sy-h, and substring history

---

tools/drip/fig_onboarding.sh

Navigation doesn't work until settings have been initialized
Moved the initialization to the beginning of the onboarding script to ensure it works throughout the onboarding.

Init settings at beginning of onboarding
